### ISSUE TITLE
setlocale fails

### ISSUE THREAD

**Issue by tgjohnst** [jpmck/chronometer2#13]
I just installed Chronometer2 v1.3 and when running, I get the following error message:
```
ning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_us.UTF-8)
```
Though I am located in the US, my Pi must have been a UK model and came configured with only the en_GB locale. I had to run `sudo dpkg-reconfigure locales` to add the en_us.UTF-8 locale before chronometer2 would run without throwing this warning. You may want to add this to the README for other users that don't have the en_US locale installed, or have a fallback option.

**Comment by jpmck** [comment]
Corrected with [54d39a](https://github.com/jpmck/chronometer2/commit/54d39a5ce9df0fb616223181cead4af5b6899447)
