### ISSUE TITLE
Script does not check for updates on other branches

### ISSUE THREAD

**Issue by RandomGuyJCI** [jpmck/chronometer2#15]
My Pi-hole is from the FTLDNS branch and whenever I do pihole -up, it says it's up to date, but in chronometer2, it says it's out of date. My guess is that it only checks for the updated version in the master branch, but not the current branch of Pi-hole.

**Comment by jpmck** [comment]
My Pi-hole, and by extension my chronometer2, runs in my house with the following goals:

- don't screw up the internet for work-from-home, and
- don't screw up the internet for my wife

For those reasons, Chronometer2 will only ever support the latest stable release of Pi-hole.
