### ISSUE TITLE
Stuck at startup - version file not found

### ISSUE THREAD

**Issue by r0ckarong** [jpmck/chronometer2#7]
I wanted to try the script, downloaded it to my raspi. When I start it I get this

```START UP====================================================
- Checking for Chronometer2 version file...
  - Chronometer2 version file not found.
- Gathering system information...
- Gathering Pi-hole information...
- Gathering network information...
- Gathering version information...
```

And there it hangs forever.

**Comment by jpmck** [comment]
Hi, the version file not existing is okay for the first start up.

Could you tell me what version of Pi-hole you are using?

You can either use ```pihole -v``` from the terminal, or find the version numbers at the corner to the web admin console.

![image](https://user-images.githubusercontent.com/6764712/27520592-cf55feb2-59dc-11e7-99a6-17a591769f74.png)

**Comment by r0ckarong** [comment]
Latest official release just like you posted.

```
  Pi-hole version is v3.1 (Latest: v3.1)
  AdminLTE version is v3.1 (Latest: v3.1)
  FTL version is v2.9.4 (Latest: v2.9.4)
```

**Comment by r0ckarong** [comment]
What I haven't mentioned is that I don't run an adafruit display but something very similar. I can't even get to setting that up though because it already hangs when I try to start it from an SSH session in a regular terminal emulator.

**Comment by jpmck** [comment]
I have been unable to replicate this. Closing.
