### ISSUE TITLE
RAM calculated incorrectly

### ISSUE THREAD

**Issue by WaLLy3K** [jpmck/chronometer2#9]
[As reported here](https://github.com/pi-hole/pi-hole/issues/2137), @Twiggy159 is experiencing an issue where the RAM is being calculated negatively.

I'm also experiencing the same issue. When using [this code](https://github.com/jpmck/chronometer2/blob/master/chronometer2.sh#L90), I get a value of `-83.8` because buff/cache isn't being calculated correctly, and for some reason, is also including available in the calculation:

```
              total        used        free      shared  buff/cache   available
Mem:        4019572      283612     1303128       53712     2432832     3652348
Swap:             0           0           0
```

This snippet should provide the correct percentage, which for me is 13:
`awk '/MemTotal:/{total=$2} /MemFree:/{free=$2} /Buffers:/{buffers=$2} /^Cached:/{cached=$2} END {printf "%.0f", (total-free-buffers-cached)*100/total}' /proc/meminfo`

Cheers! :slightly_smiling_face:

**Comment by jpmck** [comment]
This issue has been corrected in [v1.2.2](https://github.com/jpmck/chronometer2/releases/tag/v1.2.2) (see [line 92](https://github.com/jpmck/chronometer2/blob/d911d52dbfa735092d07f292bee8beba9ae5edbd/chronometer2.sh#L92)).

Thanks for the help @WaLLy3K and @Twiggy159!
